---
- name: Install ufw
  become: yes
  package:
    name: ufw
    state: present
    update_cache: yes

- name: Disable IPv6 in ufw
  become: yes
  lineinfile:
    path: /etc/default/ufw
    regex: '^IPv6\s*=\s*yes'
    state: present
    line: 'IPv6=no'

- name: Set defaults in ufw
  become: yes
  ufw: 
    default: "{{ item.default }}"
    direction: "{{ item.direction }}"
    state: enabled
  with_items:
    - { default: deny, direction: incoming }
    - { default: allow, direction: outgoing }

- name: Configure ufw
  become: yes
  ufw: 
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    state: enabled
  with_items:
    - { port: "{{ ansible_port }}", proto: tcp, rule: allow }
    - { port: http, proto: tcp, rule: allow }
    - { port: https, proto: tcp, rule: allow }
    - { port: 19999, proto: tcp, rule: allow, from_ip: 127.0.0.1 }
