# Used resources
# https://codeby.net/threads/kak-nastroit-fail2ban-dlja-zaschity-servera-apache-http.70077/
# https://www.garron.me/en/go2linux/fail2ban-protect-web-server-http-dos-attack.html
# https://technicalramblings.com/blog/how-to-add-email-notifications-to-fail2ban/

---
- name: Install fail2ban
  become: true
  package:
    name: fail2ban
    state: present
  notify: Enable fail2ban

- name: Install sendmail
  include_role:
    name: sendmail

- name: Copy configuration files
  become: true
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root
    group: root
    backup: yes
  with_items:
    - { dest: /etc/fail2ban/filter.d/http-get-dos.conf,
        src: http-get-dos.conf }
    - { dest: /etc/fail2ban/jail.local,
        src: jail.local }
    - { dest: /etc/fail2ban/action.d/sendmail-whois.local,
        src: sendmail-whois.local }
  notify: Restart fail2ban
