---
- name: Install iptables and ipset
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables
    - ipset
    - iptables-persistent

- name: Copy iptable rules
  copy:
    dest: /etc/iptables/rules.v4
    src: rules.v4
    owner: root
    group: root
  notify: Restart iptables
