---
- name: Install iptables and ipset
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables
    - ipset
    - iptables-persistent

- name: Configure iptables-persistent
  become: yes
  copy:
    dest: /etc/init.d/netfilter-persistent
    src: netfilter-persistent
    owner: root
    group: root

- name: Create new ipset  # timeout after one hour
  become: yes
  command: ipset create -exist BLACKLIST nethash timeout 3600

- name: Configure iptables
  become: yes
  copy:
    dest: /etc/iptables/rules.v4
    src: rules.v4
    owner: root
    group: root
  notify: Reload iptables
