---
- name: Configure sshd
  become: true
  replace:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: '^#?PermitRootLogin\s+[^\n]*',
        replace: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication\s+[^\n]*',
        replace: 'PasswordAuthentication no' }
  notify: Restart sshd

- name: Create ~/.ssh
  file:
    path: ~/.ssh
    state: directory
    mode: '755'

- name: Copy authorized_keys
  copy:
    dest: ~/.ssh/authorized_keys
    src: ../../../assets/rs1-ssh.pub
    mode: '640'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    backup: yes
  notify: Restart sshd

