# Resources used
# https://www.opennet.ru/docs/RUS/portsentry/portsentry4.html
# https://www.computersecuritystudent.com/UNIX/UBUNTU/1204/lesson14/index.html

---
- name: Install portsentry
  become: true
  package:
    name: portsentry
    state: present

- name: Select advanced scan detection
  become: true
  replace:
    path: /etc/default/portsentry
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: "TCP_MODE=[^\n]*", replace: TCP_MODE="atcp" }
    - { regexp: "UDP_MODE=[^\n]*", replace: UDP_MODE="audp" }
  notify: Restart portsentry

- name: Configure portsentry via /etc/portsentry/portsentry.conf
  become: true
  copy:
    dest: /etc/portsentry/portsentry.conf
    src: portsentry.conf
    owner: root
    group: root
    backup: yes
  notify: Restart portsentry

- name: Ignore current IP address 
  become: true
  lineinfile:
    path: /etc/portsentry/portsentry.ignore.static
    line: 192.168.56.1
  notify: Restart portsentry
